import { Order, Provider, Contract } from './types'

export const mockProviders: Provider[] = [
  {
    id: 'p1',
    name: 'Carlos Eduardo Mendes',
    phone: '(11) 99821-4537',
    cpf: '342.891.067-45',
    vehicleType: 'Furgão',
    vehiclePlate: 'BRA-2E19',
    status: 'ativo',
    contractSigned: true,
    contractDate: '2026-04-15',
    totalFretes: 23,
    rating: 4.9,
    createdAt: '2026-03-10',
    lastFreteDate: '2026-05-07',
    bankName: 'Nubank',
    pixKey: '342.891.067-45',
    advanceAmount: 150,
    balanceAmount: 280,
  },
  {
    id: 'p2',
    name: 'Roberto Alves da Silva',
    phone: '(11) 97634-2201',
    cpf: '571.204.938-12',
    vehicleType: 'Caminhonete',
    vehiclePlate: 'GHT-5F34',
    status: 'ativo',
    contractSigned: true,
    contractDate: '2026-04-22',
    totalFretes: 8,
    rating: 4.7,
    createdAt: '2026-04-01',
    lastFreteDate: '2026-05-08',
    bankName: 'Itaú',
    pixKey: 'roberto.silva@gmail.com',
    advanceAmount: 100,
    balanceAmount: 320,
  },
  {
    id: 'p3',
    name: 'Marcos Antônio Ferreira',
    phone: '(11) 98456-7823',
    cpf: '198.345.762-88',
    vehicleType: 'Furgão',
    vehiclePlate: 'CDE-3K77',
    status: 'ativo',
    contractSigned: true,
    contractDate: '2026-05-01',
    totalFretes: 3,
    rating: 4.8,
    createdAt: '2026-04-28',
    lastFreteDate: '2026-05-08',
    bankName: 'Bradesco',
    pixKey: '(11) 98456-7823',
    advanceAmount: 80,
    balanceAmount: 160,
  },
  {
    id: 'p4',
    name: 'Edilson Souza Barbosa',
    phone: '(11) 96521-3348',
    cpf: '423.876.019-55',
    vehicleType: 'Moto',
    vehiclePlate: 'KLM-9P02',
    status: 'adormecido',
    contractSigned: true,
    contractDate: '2026-03-05',
    totalFretes: 5,
    rating: 4.5,
    createdAt: '2026-03-01',
    lastFreteDate: '2026-04-12',
    bankName: 'PicPay',
    pixKey: '423.876.019-55',
    advanceAmount: 0,
    balanceAmount: 0,
  },
  {
    id: 'p5',
    name: 'Paulo Ricardo Nunes',
    phone: '(11) 99012-8865',
    cpf: '654.321.987-00',
    vehicleType: 'Caminhão Leve',
    vehiclePlate: 'FGH-1J44',
    status: 'adormecido',
    contractSigned: true,
    contractDate: '2026-02-18',
    totalFretes: 11,
    rating: 4.6,
    createdAt: '2026-02-10',
    lastFreteDate: '2026-04-02',
    bankName: 'C6 Bank',
    pixKey: 'paulo.nunes@hotmail.com',
    advanceAmount: 0,
    balanceAmount: 0,
  },
  {
    id: 'p6',
    name: 'Thiago Costa Lima',
    phone: '(11) 98877-4412',
    cpf: '789.012.345-67',
    vehicleType: 'Furgão',
    vehiclePlate: 'MNO-4Q88',
    status: 'adormecido',
    contractSigned: false,
    totalFretes: 1,
    rating: 4.3,
    createdAt: '2026-04-10',
    lastFreteDate: '2026-04-10',
    bankName: 'Nubank',
    pixKey: '(11) 98877-4412',
    advanceAmount: 0,
    balanceAmount: 0,
  },
]

export const mockOrders: Order[] = [
  {
    id: 'o1',
    protocol: 'FT-2026-0047',
    clientName: 'Farmácias Saúde Total',
    clientPhone: '(11) 3321-8800',
    clientEmail: 'logistica@saudetotal.com.br',
    originAddress: 'Rua das Indústrias, 450 - Distrito Industrial',
    originCity: 'Guarulhos',
    destinationAddress: 'Av. Paulista, 1234 - Bela Vista',
    destinationCity: 'São Paulo',
    cargoDescription: 'Medicamentos - carga fracionada',
    cargoWeight: '180 kg',
    status: 'em_rota',
    providerId: 'p2',
    providerName: 'Roberto Alves da Silva',
    vehiclePlate: 'GHT-5F34',
    createdAt: '2026-05-08T07:30:00',
    estimatedDelivery: '2026-05-08T14:00:00',
    trackingToken: 'tk-ft47-x9kp2m',
    collectionOrderSent: true,
    contractId: 'c1',
    value: 420,
    checkpoints: [
      {
        id: 'cp1',
        type: 'aguardando_coleta',
        description: 'Pedido criado e ordem de coleta enviada ao cliente.',
        timestamp: '2026-05-08T07:30:00',
        city: 'Guarulhos',
      },
      {
        id: 'cp2',
        type: 'coletado',
        description: 'Carga coletada no remetente. Documentos conferidos.',
        timestamp: '2026-05-08T09:15:00',
        photoUrl: '/mock-photo-coleta.jpg',
        city: 'Guarulhos',
      },
      {
        id: 'cp3',
        type: 'em_rota',
        description: 'Motorista em rota para o destino.',
        timestamp: '2026-05-08T09:22:00',
        city: 'Guarulhos',
      },
    ],
  },
  {
    id: 'o2',
    protocol: 'FT-2026-0046',
    clientName: 'Distribuidora Norte Alimentos',
    clientPhone: '(11) 4567-2200',
    clientEmail: 'compras@nortealimentos.com.br',
    originAddress: 'Rod. Anhanguera, km 18 - Galpão 7',
    originCity: 'Cajamar',
    destinationAddress: 'Rua São Bento, 89 - Centro',
    destinationCity: 'Campinas',
    cargoDescription: 'Produtos alimentícios - carga seca',
    cargoWeight: '620 kg',
    status: 'entregue',
    providerId: 'p1',
    providerName: 'Carlos Eduardo Mendes',
    vehiclePlate: 'BRA-2E19',
    createdAt: '2026-05-07T08:00:00',
    estimatedDelivery: '2026-05-07T16:00:00',
    trackingToken: 'tk-ft46-a3nw7q',
    collectionOrderSent: true,
    contractId: 'c2',
    value: 780,
    checkpoints: [
      {
        id: 'cp4',
        type: 'aguardando_coleta',
        description: 'Pedido criado e ordem de coleta enviada.',
        timestamp: '2026-05-07T08:00:00',
        city: 'Cajamar',
      },
      {
        id: 'cp5',
        type: 'coletado',
        description: 'Carga coletada. 14 volumes conferidos.',
        timestamp: '2026-05-07T09:45:00',
        photoUrl: '/mock-photo-coleta2.jpg',
        city: 'Cajamar',
      },
      {
        id: 'cp6',
        type: 'em_rota',
        description: 'Em rota para Campinas via Anhanguera.',
        timestamp: '2026-05-07T09:55:00',
        city: 'Cajamar',
      },
      {
        id: 'cp7',
        type: 'entregue',
        description: 'Entrega realizada. POD assinado pelo recebedor.',
        timestamp: '2026-05-07T14:30:00',
        photoUrl: '/mock-photo-entrega.jpg',
        city: 'Campinas',
      },
    ],
    pod: {
      signedAt: '2026-05-07T14:30:00',
      recipientName: 'Ana Paula Rodrigues',
      photoUrl: '/mock-pod.jpg',
    },
  },
  {
    id: 'o3',
    protocol: 'FT-2026-0048',
    clientName: 'TechParts Componentes',
    clientPhone: '(11) 3887-5500',
    clientEmail: 'expedicao@techparts.com.br',
    originAddress: 'Av. das Nações Unidas, 3000 - Vila Gertrudes',
    originCity: 'São Paulo',
    destinationAddress: 'Rua Industrial, 220 - Polo Industrial',
    destinationCity: 'Sorocaba',
    cargoDescription: 'Componentes eletrônicos - carga frágil',
    cargoWeight: '95 kg',
    status: 'coletado',
    providerId: 'p3',
    providerName: 'Marcos Antônio Ferreira',
    vehiclePlate: 'CDE-3K77',
    createdAt: '2026-05-08T10:00:00',
    estimatedDelivery: '2026-05-08T17:00:00',
    trackingToken: 'tk-ft48-b7vx4r',
    collectionOrderSent: true,
    contractId: 'c3',
    value: 350,
    checkpoints: [
      {
        id: 'cp8',
        type: 'aguardando_coleta',
        description: 'Pedido criado. Ordem de coleta enviada por e-mail.',
        timestamp: '2026-05-08T10:00:00',
        city: 'São Paulo',
      },
      {
        id: 'cp9',
        type: 'coletado',
        description: 'Carga coletada. Volumes lacrados conferidos.',
        timestamp: '2026-05-08T11:40:00',
        photoUrl: '/mock-photo-coleta3.jpg',
        city: 'São Paulo',
      },
    ],
  },
  {
    id: 'o4',
    protocol: 'FT-2026-0049',
    clientName: 'Gráfica Impressão Rápida',
    clientPhone: '(11) 5544-9900',
    clientEmail: 'producao@impressaorapida.com.br',
    originAddress: 'Rua Vergueiro, 1500 - Liberdade',
    originCity: 'São Paulo',
    destinationAddress: 'Av. Dom Pedro I, 400 - Jardim Paulista',
    destinationCity: 'Santo André',
    cargoDescription: 'Material gráfico - impressos',
    cargoWeight: '210 kg',
    status: 'aguardando',
    createdAt: '2026-05-08T12:00:00',
    estimatedDelivery: '2026-05-08T18:00:00',
    trackingToken: 'tk-ft49-c2yz9s',
    collectionOrderSent: false,
    value: 290,
    checkpoints: [
      {
        id: 'cp10',
        type: 'aguardando_coleta',
        description: 'Pedido criado. Aguardando alocação de motorista.',
        timestamp: '2026-05-08T12:00:00',
        city: 'São Paulo',
      },
    ],
  },
  {
    id: 'o5',
    protocol: 'FT-2026-0045',
    clientName: 'Construção e Acabamentos Silva',
    clientPhone: '(11) 2233-4455',
    clientEmail: 'obras@construcaosilva.com.br',
    originAddress: 'Rua do Comércio, 800 - Centro',
    originCity: 'Mogi das Cruzes',
    destinationAddress: 'Av. Brasil, 2200 - Jardim América',
    destinationCity: 'São Paulo',
    cargoDescription: 'Material de construção',
    cargoWeight: '850 kg',
    status: 'ocorrencia',
    providerId: 'p1',
    providerName: 'Carlos Eduardo Mendes',
    vehiclePlate: 'BRA-2E19',
    createdAt: '2026-05-06T07:00:00',
    estimatedDelivery: '2026-05-06T14:00:00',
    trackingToken: 'tk-ft45-d8mf1t',
    collectionOrderSent: true,
    contractId: 'c4',
    value: 520,
    notes: 'Destinatário não encontrado no endereço informado.',
    checkpoints: [
      {
        id: 'cp11',
        type: 'aguardando_coleta',
        description: 'Pedido criado.',
        timestamp: '2026-05-06T07:00:00',
        city: 'Mogi das Cruzes',
      },
      {
        id: 'cp12',
        type: 'coletado',
        description: 'Carga coletada.',
        timestamp: '2026-05-06T08:30:00',
        city: 'Mogi das Cruzes',
      },
      {
        id: 'cp13',
        type: 'em_rota',
        description: 'Em rota para São Paulo.',
        timestamp: '2026-05-06T08:40:00',
        city: 'Mogi das Cruzes',
      },
      {
        id: 'cp14',
        type: 'ocorrencia',
        description: 'Destinatário ausente. Tentativa de entrega sem sucesso. Aguardando instrução.',
        timestamp: '2026-05-06T12:15:00',
        photoUrl: '/mock-photo-ocorrencia.jpg',
        city: 'São Paulo',
      },
    ],
  },
  {
    id: 'o6',
    protocol: 'FT-2026-0044',
    clientName: 'Bella Moda Atacado',
    clientPhone: '(11) 3344-5566',
    clientEmail: 'logistica@bellamoda.com.br',
    originAddress: 'Rua José Paulino, 1100 - Bom Retiro',
    originCity: 'São Paulo',
    destinationAddress: 'Rua das Flores, 300 - Centro',
    destinationCity: 'Ribeirão Preto',
    cargoDescription: 'Roupas e acessórios - 32 caixas',
    cargoWeight: '440 kg',
    status: 'entregue',
    providerId: 'p1',
    providerName: 'Carlos Eduardo Mendes',
    vehiclePlate: 'BRA-2E19',
    createdAt: '2026-05-05T06:30:00',
    estimatedDelivery: '2026-05-05T15:00:00',
    trackingToken: 'tk-ft44-e5nh6u',
    collectionOrderSent: true,
    contractId: 'c5',
    value: 650,
    checkpoints: [
      {
        id: 'cp15',
        type: 'aguardando_coleta',
        description: 'Pedido criado.',
        timestamp: '2026-05-05T06:30:00',
        city: 'São Paulo',
      },
      {
        id: 'cp16',
        type: 'coletado',
        description: '32 caixas coletadas e conferidas.',
        timestamp: '2026-05-05T07:50:00',
        city: 'São Paulo',
      },
      {
        id: 'cp17',
        type: 'em_rota',
        description: 'Em rota via Rodovia Anhanguera.',
        timestamp: '2026-05-05T08:05:00',
        city: 'São Paulo',
      },
      {
        id: 'cp18',
        type: 'entregue',
        description: 'Entrega concluída. POD assinado.',
        timestamp: '2026-05-05T13:20:00',
        city: 'Ribeirão Preto',
      },
    ],
    pod: {
      signedAt: '2026-05-05T13:20:00',
      recipientName: 'Marcos Roberto Cunha',
      photoUrl: '/mock-pod2.jpg',
    },
  },
  {
    id: 'o7',
    protocol: 'FT-2026-0038',
    clientName: 'Metalúrgica Souza Ltda.',
    clientPhone: '(11) 4499-1122',
    clientEmail: 'compras@metalurgicasouza.com.br',
    originAddress: 'Rod. SP-101, km 5 - Galpão 3',
    originCity: 'Americana',
    destinationAddress: 'Rua Marechal Deodoro, 510 - Centro',
    destinationCity: 'Jundiaí',
    cargoDescription: 'Peças metálicas',
    cargoWeight: '310 kg',
    status: 'entregue',
    providerId: 'p4',
    providerName: 'Edilson Souza Barbosa',
    vehiclePlate: 'KLM-9P02',
    createdAt: '2026-04-12T08:00:00',
    estimatedDelivery: '2026-04-12T15:00:00',
    trackingToken: 'tk-ft38-p4abc1',
    collectionOrderSent: true,
    contractId: 'c6',
    value: 280,
    checkpoints: [
      { id: 'cp19', type: 'aguardando_coleta', description: 'Pedido criado.', timestamp: '2026-04-12T08:00:00', city: 'Americana' },
      { id: 'cp20', type: 'coletado', description: 'Carga coletada.', timestamp: '2026-04-12T09:20:00', city: 'Americana' },
      { id: 'cp21', type: 'em_rota', description: 'Em rota para Jundiaí.', timestamp: '2026-04-12T09:30:00', city: 'Americana' },
      { id: 'cp22', type: 'entregue', description: 'Entrega realizada. POD assinado.', timestamp: '2026-04-12T13:45:00', city: 'Jundiaí' },
    ],
    pod: { signedAt: '2026-04-12T13:45:00', recipientName: 'José Carlos Ferreira', photoUrl: '/mock-pod3.jpg' },
  },
  {
    id: 'o8',
    protocol: 'FT-2026-0021',
    clientName: 'Atacado Bebidas Sul',
    clientPhone: '(11) 3322-7788',
    clientEmail: 'logistica@bebidasul.com.br',
    originAddress: 'Av. Industrial, 900 - Distrito Industrial',
    originCity: 'São José dos Campos',
    destinationAddress: 'Rua das Palmeiras, 88 - Centro',
    destinationCity: 'Taubaté',
    cargoDescription: 'Bebidas - carga fria',
    cargoWeight: '520 kg',
    status: 'entregue',
    providerId: 'p5',
    providerName: 'Paulo Ricardo Nunes',
    vehiclePlate: 'FGH-1J44',
    createdAt: '2026-04-02T07:00:00',
    estimatedDelivery: '2026-04-02T13:00:00',
    trackingToken: 'tk-ft21-p5xyz2',
    collectionOrderSent: true,
    contractId: 'c7',
    value: 490,
    checkpoints: [
      { id: 'cp23', type: 'aguardando_coleta', description: 'Pedido criado.', timestamp: '2026-04-02T07:00:00', city: 'São José dos Campos' },
      { id: 'cp24', type: 'coletado', description: 'Carga coletada.', timestamp: '2026-04-02T08:10:00', city: 'São José dos Campos' },
      { id: 'cp25', type: 'em_rota', description: 'Em rota para Taubaté.', timestamp: '2026-04-02T08:20:00', city: 'São José dos Campos' },
      { id: 'cp26', type: 'entregue', description: 'Entrega concluída. POD assinado.', timestamp: '2026-04-02T11:55:00', city: 'Taubaté' },
    ],
    pod: { signedAt: '2026-04-02T11:55:00', recipientName: 'Roberta Lins', photoUrl: '/mock-pod4.jpg' },
  },
  {
    id: 'o9',
    protocol: 'FT-2026-0033',
    clientName: 'Agropecuária Nunes',
    clientPhone: '(11) 4412-3300',
    clientEmail: 'compras@agronunes.com.br',
    originAddress: 'Estrada Municipal, km 12',
    originCity: 'Itu',
    destinationAddress: 'Av. Getúlio Vargas, 300 - Centro',
    destinationCity: 'Sorocaba',
    cargoDescription: 'Insumos agrícolas',
    cargoWeight: '680 kg',
    status: 'entregue',
    providerId: 'p6',
    providerName: 'Thiago Costa Lima',
    vehiclePlate: 'MNO-4Q88',
    createdAt: '2026-04-10T09:00:00',
    estimatedDelivery: '2026-04-10T14:00:00',
    trackingToken: 'tk-ft33-p6def3',
    collectionOrderSent: true,
    value: 310,
    checkpoints: [
      { id: 'cp27', type: 'aguardando_coleta', description: 'Pedido criado.', timestamp: '2026-04-10T09:00:00', city: 'Itu' },
      { id: 'cp28', type: 'coletado', description: 'Carga coletada.', timestamp: '2026-04-10T10:15:00', city: 'Itu' },
      { id: 'cp29', type: 'em_rota', description: 'Em rota para Sorocaba.', timestamp: '2026-04-10T10:25:00', city: 'Itu' },
      { id: 'cp30', type: 'entregue', description: 'Entrega realizada.', timestamp: '2026-04-10T13:10:00', city: 'Sorocaba' },
    ],
    pod: { signedAt: '2026-04-10T13:10:00', recipientName: 'Fernando Augusto', photoUrl: '/mock-pod5.jpg' },
  },
]

export const mockContracts: Contract[] = [
  {
    id: 'c1',
    providerId: 'p2',
    providerName: 'Roberto Alves da Silva',
    orderId: 'o1',
    orderProtocol: 'FT-2026-0047',
    clientName: 'Farmácias Saúde Total',
    originCity: 'Guarulhos',
    destinationCity: 'São Paulo',
    value: 420,
    advanceAmount: 100,
    createdAt: '2026-05-08T07:30:00',
    signedAt: '2026-05-08T07:48:00',
    status: 'assinado',
  },
  {
    id: 'c2',
    providerId: 'p1',
    providerName: 'Carlos Eduardo Mendes',
    orderId: 'o2',
    orderProtocol: 'FT-2026-0046',
    clientName: 'Distribuidora Norte Alimentos',
    originCity: 'Cajamar',
    destinationCity: 'Campinas',
    value: 780,
    advanceAmount: 150,
    createdAt: '2026-05-07T08:00:00',
    signedAt: '2026-05-07T08:12:00',
    status: 'encerrado',
  },
  {
    id: 'c3',
    providerId: 'p3',
    providerName: 'Marcos Antônio Ferreira',
    orderId: 'o3',
    orderProtocol: 'FT-2026-0048',
    clientName: 'TechParts Componentes',
    originCity: 'São Paulo',
    destinationCity: 'Sorocaba',
    value: 350,
    advanceAmount: 80,
    createdAt: '2026-05-08T10:00:00',
    signedAt: '2026-05-08T10:15:00',
    status: 'assinado',
  },
  {
    id: 'c4',
    providerId: 'p1',
    providerName: 'Carlos Eduardo Mendes',
    orderId: 'o5',
    orderProtocol: 'FT-2026-0045',
    clientName: 'Construção e Acabamentos Silva',
    originCity: 'Mogi das Cruzes',
    destinationCity: 'São Paulo',
    value: 520,
    advanceAmount: 150,
    createdAt: '2026-05-06T07:00:00',
    signedAt: '2026-05-06T07:18:00',
    status: 'encerrado',
  },
  {
    id: 'c5',
    providerId: 'p1',
    providerName: 'Carlos Eduardo Mendes',
    orderId: 'o6',
    orderProtocol: 'FT-2026-0044',
    clientName: 'Bella Moda Atacado',
    originCity: 'São Paulo',
    destinationCity: 'Ribeirão Preto',
    value: 650,
    advanceAmount: 150,
    createdAt: '2026-05-05T06:30:00',
    signedAt: '2026-05-05T06:45:00',
    status: 'encerrado',
  },
  {
    id: 'c6',
    providerId: 'p4',
    providerName: 'Edilson Souza Barbosa',
    orderId: 'o7',
    orderProtocol: 'FT-2026-0038',
    clientName: 'Metalúrgica Souza Ltda.',
    originCity: 'Americana',
    destinationCity: 'Jundiaí',
    value: 280,
    advanceAmount: 80,
    createdAt: '2026-04-12T08:00:00',
    signedAt: '2026-04-12T08:14:00',
    status: 'encerrado',
  },
  {
    id: 'c7',
    providerId: 'p5',
    providerName: 'Paulo Ricardo Nunes',
    orderId: 'o8',
    orderProtocol: 'FT-2026-0021',
    clientName: 'Atacado Bebidas Sul',
    originCity: 'São José dos Campos',
    destinationCity: 'Taubaté',
    value: 490,
    advanceAmount: 100,
    createdAt: '2026-04-02T07:00:00',
    signedAt: '2026-04-02T07:11:00',
    status: 'encerrado',
  },
]

export function getOrderById(id: string) {
  return mockOrders.find(o => o.id === id)
}

export function getOrderByToken(token: string) {
  return mockOrders.find(o => o.trackingToken === token)
}

export function getProviderById(id: string) {
  return mockProviders.find(p => p.id === id)
}

export function getContractById(id: string) {
  return mockContracts.find(c => c.id === id)
}

export function getOrdersByProvider(providerId: string) {
  return mockOrders.filter(o => o.providerId === providerId)
}

export const dashboardStats = {
  totalHoje: 4,
  emRota: 1,
  entregues: 1,
  ocorrencias: 1,
  coletados: 1,
  aguardando: 1,
  prestadoresAtivos: 3,
  prestadoresAdormecidos: 3,
  receitaSemana: 2770,
}
